app/models.py
from . import db, login_manager
import datetime
from flask import Flask,request
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    password_hash = db.Column(db.String(255))
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    posts = db.relationship('Post', backref='user', lazy="dynamic")


    pass_secure  = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    image_url = db.Column(db.String(255))
    title = db.Column(db.String(255))
    content = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow) 
    comments = db.relationship('Comment', backref='post', lazy='dynamic')   

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_posts(cls):
        rows = Post.query.all()
        return rows

    @classmethod
    def get_post(cls, id):
        row = Post.query.filter_by(id=id).first()
        return row   

    @classmethod
    def get_my_posts(cls, id):
        rows = Post.query.filter_by(user_id=id).all()
        return rows

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    message = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    post_id = db.Column(db.Integer, db.ForeignKey("posts.id"))
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    # @classmethod
    # def get_comments(cls):
    #     rows = Comment.query.all()
    #     return rows

    @classmethod
    def get_comments_by_post_id(cls, id):
        rows = Comment.query.filter_by(post_id=id).all()
        return rows

    @classmethod
    def delete_comment_by_id(cls, id):
        single_comment = Comment.query.filter_by(id = id).first()

        db.session.delete(single_comment)
        db.session.commit()


    @classmethod
    def get_post_by_comment_id(cls, id):
        rows = Comment.query.filter_by(post_id=id).all()
        return rows    

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()


def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)

    Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)
    login_manager.session_protection = 'strong'
    login_manager.login_view = 'auth.login'

    migrate = Migrate(app, db)

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/home/__init__.py
from flask import render_template, Blueprint

home = Blueprint('home',__name__)

from . import views

app/home/views.py
from flask import render_template,request,redirect,url_for
from flask_login import login_required
from ..models import Post,Comment

from . import home


@home.route('/')
def index():

    rows = Post.get_posts()

    id = []
    title = []
    content = []
    image_url = []
    created_at = []


    for row in rows:
        id.append(row.id)
        title.append(row.title)
        content.append(row.content)
        image_url.append(row.image_url)
        created_at.append(row.created_at)

    mylist = zip(id, title, content, image_url, created_at)

    return render_template('home/index.html', myposts=mylist)

@home.route('/add_post', methods=['GET', 'POST'])
def add_post_form():

    if request.method == 'POST':
        title = request.form.get('title')
        image_url = request.form.get('image_url')
        content = request.form.get('content')
        user_id = request.form.get('user_id')

        post = Post(title=title, image_url=image_url, content=content, user_id=user_id)
        post.save_post()

        return render_template("home/add_post.html", title="Add Post", message="Post added")

    return render_template("home/add_post.html")

@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

@home.route('/profile/<int:id>')
@login_required
def profile(id):    
    """
    Render the dashboard template on the /dashboard route
    """

    return render_template('home/profile.html', title="Profile")

@home.route('/post/<int:id>', methods=['GET','POST'])
@login_required
def single_post(id):
    """
    Render the dashboard template on the /dashboard route
    """
    post = Post.get_post(id)
    rows = Comment.get_comments_by_post_id(post.id)

    id = []
    message = []
    created_at = []


    for row in rows:
        id.append(row.id)
        message.append(row.message)
        created_at.append(row.created_at)

    mycomments = zip(id, message, created_at)

    if request.method == 'POST':
        message = request.form.get('message')
        user_id = request.form.get('user_id')
        post_id = post.id

        comment = Comment(message=message, user_id=user_id, post_id=post_id)
        comment.save_comment()

        return redirect(url_for('home.single_post', id=post.id))

    return render_template('home/single_post.html', title="Post", post=post, comments=mycomments)


@home.route('/new-post',  methods=['GET', 'POST'])
@login_required
def new_post():
    """
    Render the dashboard template on the /dashboard route
    """
    if request.method == 'POST':
        title = request.form.get('title')
        image_url = request.form.get('image_url')
        content  = request.form.get('content')
        user_id = request.form.get('user_id')

        post = Post(title=title, image_url=image_url, content=content, user_id=user_id)
        post.save_post()

        return render_template('home/add_post.html', title="New Post", message="Post added.")

    return render_template('home/add_post.html', title="New Post")


@home.route('/delete-comment/<int:id>/<int:post>')
@login_required
def delete_comment(id, post):   
    """
    Render the dashboard template on the /dashboard route
    """
    Comment.delete_comment_by_id(id)

    return redirect(url_for('home.single_post', id=post))
   


    

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Styles block -->

{% block styles%}
{{ super() }}
<link href="https://fonts.googleapis.com/css2?family=Grenze+Gotisch:wght@500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}">
{% endblock %}

<!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/home/add_comment.html
{% extends 'base.html'%}
<!-- Content block -->
{% block content %}
<form method="POST">
    <div class="form-group">
        <textarea class="form-control" name="content" rows="3" placeholder="Write comment here..."></textarea><td>
    </div>
    <input type="hidden" name="user_id" value="{{current_user.id}}" />
</form>


{% endblock%}

app/templates/home/add_post.html
{% extends 'base.html'%}

<!-- Content block -->
{% block content %}

<div class="container">

    {% if message%}
    <div class="alert alert-success">
        <strong>Success!</strong> {{message}}
    </div>
      
    {%endif%}

    <form method="POST">
        <div class="form-group">
            <input type="text" name="title" class="form-control" placeholder="Title">
        </div>    
        <div class="form-group">
            <input type="text" name="image_url" class="form-control" placeholder="image_url"><td>
        </div>        
        <div class="form-group">
            <textarea class="form-control" name="content" rows="3" placeholder="Write post here..."></textarea><td>
        </div>
        <input type="hidden" name="user_id" value="{{current_user.id}}" />
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>

</div>

<div class="container">

</div>

{% endblock%}

app/templates/home/dashboard.html
{% extends 'base.html'%}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h3> Hello {{current_user.username}} </h3>
        </div>
    </div>  
    <div class="row">
        <div class="col-lg-3 img-container">
            <img src="{{image_url}}" alt="">
            <small>Posted {{created_at}}</small>
            <p>{{title}}</p>
        </div>
    </div>
    <footer>
        <div class="row">
            <div class="col-lg-12 text-center">
                <p class="copyright text-muted">Copyright &copy; Nguthism 2020</p>
            </div>
        </div>
    </footer>
</div>


{% endblock%}

app/templates/home/index.html
{% extends 'base.html'%}

{% block content %}

<div class="container">
    <div class="row">
        {% for id, title, content, image_url, created_at in myposts %}
        <div class="col-lg-3 img-container">
            <a href="{{url_for('home.single_post',id=id)}}">
                <img src="{{image_url}}" alt="">
                <small>Posted {{created_at}}</small>
                <p>{{title}}</p>
            </a>
        </div>
        {% endfor %}
    </div>
    <footer>
        <div class="row">
            <div class="col-lg-12 text-center">
                <p class="copyright text-muted">Copyright &copy; Nguthism 2020</p>
            </div>
        </div>
    </footer>
</div>


{% endblock%}

app/templates/home/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-lg-12">
    <h3> Hello {{current_user.username}} </h3>
  </div>
</div>
</div>
{% endblock %}

app/templates/home/single_post.html
{% extends 'base.html'%}

<!-- Content block -->
{% block content %}


<div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>{{post.title}}</h1>
        <img src="{{post.image_url}}" alt="post" />

        <p>{{post.content}}</p>

        <small>{{post.created_at}}</small>

        <hr/>

        <h3>Comments</h3>

        {% for id, message, created_at in comments  %}        
        <div >
           <p style="margin-bottom: 0; margin-top: 10px;">{{message}}</p>
        </div>
        <a href="{{url_for('home.delete_comment',id=id,post=post.id)}}">
          <button type="button" class="btn btn-danger">Delete</button>
        </a>
        {% endfor %}

        <form method="POST">
          <input type="hidden" name="user_id" value="{{current_user.id}}" />
          <div class="form-group" style="margin-top: 10px;">
            <textarea class="form-control" rows="5" placeholder="Write comment here..." name="message"></textarea>
          </div>
          
          <div class="form-group">
            <button class="btn btn-primary" type="submit">Post</button>
          </div>
        </form>
      </div>
    </div>
  </div>


  {% endblock%}
  

app/templates/index.html
<!-- <h3>dgfdgfjhgkjhk</h3>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <p class="copyright text-muted">Copyright &copy; Nguthism 2020</p>
            </div>
        </div>
    </div>
</footer> -->

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Nguthism</a>
      </div>
      <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <li><a href="/">Home</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{url_for('home.new_post')}}">New post</a>            
            <li><a href="{{url_for('home.dashboard')}}">Dashboard</a>
            <li><a href="{{url_for('home.profile',id=current_user.id)}}">Profile</a></li>
            <li><a href="{{url_for('auth.logout')}}">Logout</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Login</a></li>
            <li><a href="{{url_for('auth.register')}}">Sign Up</a></li>
            {%endif%}
          </ul>
      </div>
  </div>
</div>